type Berry implements Node {
    id: ID!
    itemID: ID!
    identifier: String!
    name: String!
    shortEffect: String!
    effect: String!
    cost: Int!
    flingPower: Int
    flingEffect: ItemFlingEffect
    category: ItemCategory!
    flags: [ItemFlag]!
    flavorText(versionGroup: Int = 17): ItemFlavorText!
    naturalGiftPower: Int!
    size: Int!
    maxharvest: Int!
    growthTime: Int!
    soilDryness: Int!
    smoothness: Int! 
    firmness: BerryFirmness
    flavors: [BerryFlavor]!
}

type BerryFirmness {
    identifier: String!
    name: String!
}

type BerryFlavor {
    name: String!
    potency: Int!
    contestType: ContestType
}

type BerryEdge {
    cursor: Cursor!
    node: Berry
}

type BerryConnection {
    totalCount: Int!
    edges: [BerryEdge]
    pageInfo: PageInfo!
}
