type Generation implements Node {
    id: ID!
    identifier: String!
    name: String!
    region: Region!
}

type GenerationEdge {
	cursor: Cursor!
	node: Generation
}

type GenerationConnection {
	totalCount: Int!
	edges: [GenerationEdge]
	pageInfo: PageInfo!
}
