type Item implements Node {
    id: ID!
    identifier: String!
    name: String!
    shortEffect: String!
    effect: String!
    cost: Int!
    flingPower: Int
    flingEffect: ItemFlingEffect
    category: ItemCategory!
    flags: [ItemFlag]!
    flavorText(versionGroup: Int = 17): ItemFlavorText!
}

type ItemFlingEffect {
    identifier: String!
    effect: String!
}

type ItemCategory {
    identifier: String!
    name: String!
    pocket: ItemPocket!
}

type ItemPocket {
    identifier: String!
    name: String!
}

type ItemFlag {
    identifier: String!
    name: String!
    description: String!
}

type ItemFlavorText {
    versionGroup: VersionGroup
    text: String!
}

type ItemEdge {
    cursor: Cursor!
    node: Item
}

type ItemConnection {
    totalCount: Int!
    edges: [ItemEdge]
    pageInfo: PageInfo!
}
